from typing import Any, List, Protocol, runtime_checkable, Dict, Optional, Union

# Forward declarations or TypeVar can be used if needed,
# but for now we rely on explicit imports in implementation files
# or loose coupling via 'Any' where strict circular dependency exists.

@runtime_checkable
class LexerProtocol(Protocol):
    def get_next_token(self) -> Any: ...
    def peek(self) -> Optional[str]: ...
    def advance(self) -> None: ...

@runtime_checkable
class ParserProtocol(Protocol):
    def parse_program(self) -> Any: ...
    def parse_expression(self, precedence: int) -> Any: ...
    def register_prefix(self, token_type: Any, fn: Any) -> None: ...
    def register_infix(self, token_type: Any, fn: Any, precedence: int) -> None: ...
    def register_token_handler(self, token_value: str, fn: Any) -> None: ...
    def eat(self, token_type: Any) -> None: ...

@runtime_checkable
class ContextProtocol(Protocol):
    @property
    def symbols(self) -> Dict[str, Any]: ...
    @property
    def functions(self) -> Dict[str, Any]: ...
    @property
    def modules(self) -> Dict[str, Any]: ...

    def get(self, name: str) -> Any: ...
    def set(self, name: str, value: Any) -> None: ...
    def register_function(self, name: str, func: Any) -> None: ...
    def call_function(self, name: str, args: List[Any], interpreter: 'InterpreterProtocol') -> Any: ...

@runtime_checkable
class InterpreterProtocol(Protocol):
    @property
    def context(self) -> ContextProtocol: ...

    def visit(self, node: Any) -> Any: ...
    def register_visitor(self, node_type: Any, handler: Any) -> None: ...
    def interpolate_string(self, s: str) -> str: ...
    def evaluate_args(self, args_nodes: List[Any]) -> List[Any]: ...
